// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjHCiPpvLeo71HZr1JpnScZJ20AaSY1A',
    appId: '1:600699247290:web:74fae4e6c6b87d497a8083',
    messagingSenderId: '600699247290',
    projectId: 'life-ai-f464e',
    authDomain: 'life-ai-f464e.firebaseapp.com',
    storageBucket: 'life-ai-f464e.firebasestorage.app',
    measurementId: 'G-GBVZNGQ4GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoKwS0XnlUCQU6yOdnKTJ729DhP4VxjK0',
    appId: '1:600699247290:android:3b4db8a4a26a0b9f7a8083',
    messagingSenderId: '600699247290',
    projectId: 'life-ai-f464e',
    storageBucket: 'life-ai-f464e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhQOp82RansnNu51QaaQRl-waQgh_-WI',
    appId: '1:600699247290:ios:ea67ac9c599b9a557a8083',
    messagingSenderId: '600699247290',
    projectId: 'life-ai-f464e',
    storageBucket: 'life-ai-f464e.firebasestorage.app',
    iosBundleId: 'com.example.lifeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkhQOp82RansnNu51QaaQRl-waQgh_-WI',
    appId: '1:600699247290:ios:ea67ac9c599b9a557a8083',
    messagingSenderId: '600699247290',
    projectId: 'life-ai-f464e',
    storageBucket: 'life-ai-f464e.firebasestorage.app',
    iosBundleId: 'com.example.lifeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtjHCiPpvLeo71HZr1JpnScZJ20AaSY1A',
    appId: '1:600699247290:web:fb416d0ec1cdd3a07a8083',
    messagingSenderId: '600699247290',
    projectId: 'life-ai-f464e',
    authDomain: 'life-ai-f464e.firebaseapp.com',
    storageBucket: 'life-ai-f464e.firebasestorage.app',
    measurementId: 'G-E95T70JGCP',
  );
}
